# Generated by Django 4.1 on 2022-09-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='displaydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('enabled', models.CharField(default='yes', max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200, unique=True)),
                ('pwd', models.CharField(max_length=200)),
                ('ufullname', models.CharField(max_length=200)),
                ('uemail', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('unic', models.CharField(max_length=200)),
                ('uaddress', models.CharField(max_length=200)),
                ('utelephone', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
                ('udob', models.DateField()),
                ('verified', models.CharField(default='yes', max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_product_provider',
            fields=[
                ('t_product_provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enabled', models.CharField(max_length=10)),
                ('rating', models.IntegerField(verbose_name=200)),
                ('location', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('volunteer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('long', models.IntegerField()),
                ('width', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('modification_date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommtradingapp.t_products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='ecommtradingapp.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_consumptions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('enabled', models.CharField(default='yes', max_length=10)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='ecommtradingapp.t_products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user1', to='ecommtradingapp.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_announcements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=400)),
                ('creation_date', models.DateField()),
                ('modification_date', models.DateField()),
                ('t_product_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrovider2', to='ecommtradingapp.t_product_provider')),
            ],
        ),
    ]
