# Generated by Django 4.1 on 2022-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommtradingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaydata',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='t_consumptions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
