# Generated by Django 4.1 on 2022-09-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommtradingapp', '0002_remove_displaydata_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_consumptions',
            name='status',
            field=models.CharField(default='Progress', max_length=20),
        ),
    ]
