# Generated by Django 4.1.3 on 2022-11-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommtradingapp', '0003_alter_t_consumptions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_product_provider',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='t_product_provider',
            name='enabled',
            field=models.CharField(default='yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='t_product_provider',
            name='modification_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='t_product_provider',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='t_product_provider',
            name='t_product_provider_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
