# Generated by Django 4.1.3 on 2022-11-24 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommtradingapp', '0005_t_consumptions_product_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_consumptions',
            name='product_provider_id',
        ),
    ]
